### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by P34enKa**

### CODE REVIEW

**Comment by AOMIAOMAO** [comment]
Thank you so much!, but would you be willing to make a translation like this for the fabric version?

**Comment by P34enKa** [comment]
Sorry, I didn't notice that the Forge port is made by different people. Here you go

**Comment by AOMIAOMAO** [comment]
Thanks!

**Comment by AOMIAOMAO** [comment]
> Sorry, I didn't notice that the Forge port is made by different people. Here you go

This is [the forge version](https://github.com/Minecraft-LightLand/BarbequesDelight), please submit translations of the forge version here，thanks！

**Pull request merged**
